[Feat] #8 PageViewController와 SegmentedControl 연결
DeveloperAcademy-POSTECH/MacC-Team-Spacer pull request #18
Opened 2022-10-21 06:10 UTC by bee712

## 세부 사항
- PageViewController(파일 내 변수명은 pageController)에 보여줄 ViewController를 추가하였습니다
- PageViewController에 오토 레이아웃을 적용했습니다
- PageViewController에 페이지 이동 시 ViewController가 바뀌게 됩니다
- PageViewController의 ViewController가 바뀌면 SegmentedControl(파일 내 변수명 segmentedControl)에 선택된 요소도 바뀌게 됩니다
- SegmentedCotnrol에 선택된 요소가 바뀌면 PageViewControl에서 보여주는 ViewController가 바뀝니다

|CafeDetailView|
|:---:|
|![Simulator Screen Recording - iPhone 13 - 2022-10-21 at 15 05 14](https://user-images.githubusercontent.com/48711413/197124174-8bd3a782-4cf8-4b5e-8720-20391d0cab09.gif)|

## 특이사항
- PageViewController를 스와이프하거나 SegmentedControl의 요소를 터치하는 방식 두 가지 모두 ViewController를 변경시킬 수 있으나, 페이지가 넘어갈 때의 애니메이션이 두 방식에 차이가 있습니다.
  - PageViewController를 스와이프하는 경우, ViewController가 변경되고 애니메이션이 멈췄을 때 선택된 segment가 변경됩니다
  - SegmentedContrl을 이용할 경우, segment 터치와 동시에 ViewController 이동 애니메이션이 시작됩니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 
대하여 알고 있습니다.

2022-10-21 06:30 UTC, hurdasol98 approved these changes
LGTM

2022-10-22 03:48 UTC, M1zz requested changes
코멘트 한 번 확인 부탁드릴게요

2022-10-22 03:48 UTC, M1zz commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
> +        self.scrollView.addSubview(self.dynamicStackView)
self가 없으면 어떻게 되나요?

2022-10-22 03:48 UTC, M1zz commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
>          ]
이거 빌드에러 안나요? } 가 있어야 할 자리같은데...

2022-10-22 07:12 UTC, bee712 commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
>          ]
적용될 constraint를 배열로 저장한거라 따로 빌드 에러는 나지 않았습니다!

2022-10-22 07:16 UTC, bee712 commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
> +        self.scrollView.addSubview(self.dynamicStackView)
self를 붙이지 않아도 정상적으로 작동합니다! 보통 self를 많이 붙여서 사용해서 사용했던 건데 특별히 self로 구분 지어줄 필요가 없는 경우에는 쓰지 않는 편이 나을까요?

2022-10-24 00:19 UTC, M1zz commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
> +        self.scrollView.addSubview(self.dynamicStackView)
네 스위프트 스럽지 않은 코드라고 생각합니다. 문법적으로는 틀리지 않지만 스위프트 스럽지 않은 스타일을 익히는 것에도 주의 해야합니다!

2022-10-24 00:20 UTC, M1zz approved these changes

2022-10-24 02:23 UTC, bee712 commented on Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
> +        self.scrollView.addSubview(self.dynamicStackView)
아하 이해했습니다 무조건 붙인다고 좋은 코드가 아니었군요.
d449f19d57d8e23a9f883e6333e37933d382455d 해당 커밋에 수정사항 반영했습니다 감사합니다!

2022-10-24 03:16 UTC, merged